version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_api_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - redis
    networks:
      - laravel
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000

  web:
    image: nginx:alpine
    container_name: laravel_api_web
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: laravel_api_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base
      MYSQL_USER: base
      MYSQL_PASSWORD: base
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  redis:
      image: redis:alpine
      container_name: laravel_api_redis
      ports:
          - "6379:6379"
      networks:
          - laravel

networks:
  laravel:

volumes:
  dbdata:
