version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_api_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    networks:
      - laravel
    entrypoint: ["sh", "/var/www/html/scripts/entrypoint.sh"]

  web:
    image: nginx:alpine
    container_name: laravel_api_web
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: laravel_api_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-api
      MYSQL_USER: laravel-api
      MYSQL_PASSWORD: laravel-api
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel

  redis:
      image: redis:alpine
      container_name: laravel_api_redis
      ports:
          - "6379:6379"
      networks:
          - laravel

networks:
  laravel:

volumes:
  dbdata:
